development:
  adapter: postgresql
  encoding: unicode
  database: family-facebook_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: family-facebook_test
  pool: 5
  username: 
  password: 